disproved/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('login/', admin.site.urls),
    path('', include('facts.urls'), name='facts'),
]

facts/urls.py
from django.urls import path
from facts import views

app_name = 'facts'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('random/', views.random, name='random'),
    path('facts/<int:question_id>/', views.detail, name='detail'),
]

facts/models.py
from django.db import models

class Tag(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name

class Fact(models.Model):
    name = models.CharField(max_length=255)
    year = models.IntegerField(null=True, blank=True)
    description = models.TextField()
    tags = models.ManyToManyField(Tag, blank=True)
    proof_link = models.URLField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.name
    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Fact'
        verbose_name_plural = 'Facts'

facts/views.py
from multiprocessing import context
from django.shortcuts import render, get_object_or_404

from facts.models import Fact


def index(request):
    year = request.GET.get('year', None)
    if year:
        facts_list = Fact.objects.filter(year__gte=year).order_by('year')
        context = {'facts_list': facts_list}
        return render(request, 'facts/index.html', context)
    return render(request, 'facts/index.html')


def detail(request, question_id):
    fact = get_object_or_404(Fact, pk=question_id)
    return render(request, 'facts/detail.html', {'fact': fact})

def random(request):
    fact = Fact.objects.order_by('?').first()
    return render(request, 'facts/detail.html', {'fact': fact})

def about(request):
    return render(request, 'facts/about.html')

facts/templates/facts/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>What school facts have been disproved</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light py-3 mb-3">
      <div class="container">
        <a class="navbar-brand" href="/">&#10060 Disproved</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link"  href="{% url 'facts:random' %}" title="Random fact">Random</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
          </ul>
          <span class="navbar-text">
            Your knowledge is becoming outdated by the day
          </span>
        </div>
      </div>
    </nav>

    {% block content %}
    {% endblock content %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </body>
</html>

facts/templates/facts/detail.html
{% extends "facts/base.html" %} {% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col col-4">
      <div class="card" style="width: 18rem">
        <div class="card-body">
          <h5 class="card-title">{{fact.name}}</h5>
          <h6 class="card-subtitle mb-2 text-muted">{{fact.year}}</h6>
          <p class="card-text">{{fact.description}}</p>
          <a href="{{fact.proof_link}}" class="card-link">Proof link</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

facts/templates/facts/index.html
{% extends "facts/base.html" %} {% block content %}
<div class="container container-fluid pb-3">
  <div class="row justify-content-center">
    <div class="col col-lg-4 p-2">
      <h1>Enter the year in which you graduated</h1>

      <form method="GET" action="{{ request.path }}">
        <div class="input-group mb-3">
          <input
            type="text"
            class="form-control"
            placeholder="Year"
            aria-label="Recipient's username"
            aria-describedby="button-addon2"
            name="year"
          />
          <button
            class="btn btn-outline-secondary"
            type="button"
            id="button-addon2"
          >
            Check
          </button>
        </div>
      </form>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col col-lg-4">
      {% if facts_list %}
      <ul>
        {% for fact in facts_list %}
        <li><a href="{% url 'facts:detail' fact.id %}">{{ fact.name }}</a></li>
        {% endfor %}
      </ul>
      {% else %}
      <p>Have not yet to disprove anything</p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock content %}